---

- name: Add Grafana repo(Centos/Redhat)
  yum_repository:
    name: grafana
    description: grafana repo
    baseurl: https://packagecloud.io/grafana/stable/el/6/$basearch
    gpgcheck: yes
    gpgkey: https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
  when: ansible_os_family == "RedHat"


- name: Install grafana
  yum:
    name: grafana
  when: ansible_os_family == "RedHat"


- name: Add apt repository
  apt_repository:
    repo: 'deb https://packagecloud.io/grafana/stable/debian/ wheezy main'  #TODO: remove hardcode version number
  when: ansible_distribution == "Ubuntu"

- name: Add grafana apt key
  apt_key:
    url: https://packagecloud.io/grafana/stable/gpgkey
  when: ansible_distribution == "Ubuntu"


- name: Install grafana
  apt:
    name: grafana
    update_cache: yes
  when: ansible_distribution == "Ubuntu"


- name: Ensure grafana started
  service:
    name: grafana-server
    state: started
