---

- name: Install InfluxDB
  hosts: influx
  become: yes
  roles:
    - influxdb
  tags:
    - influxdb


- name: Install Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags:
    - grafana
